### ISSUE TITLE
Mia's story isn't complete

### ISSUE THREAD

**Issue by maj113** [maj113/Rizzinator#5]
There is also no interaction implemented between characters and players

**Comment by halal-beef** [comment]
What the fuck is this

**Comment by maj113** [comment]
> What the fuck is this

you think i know?

**Comment by halal-beef** [comment]
Yeah cause u made the repo busta

**Comment by maj113** [comment]
> Yeah cause u made the repo busta

dude i was high as fuckkkkk brahj

**Comment by halal-beef** [comment]
aaaaa xaxaxaxa i get it

**Comment by halal-beef** [comment]
i just realised u created this issue on my bday

**Comment by maj113** [comment]
https://tenor.com/view/nuh-uh-beocord-no-lol-gif-24435520

**Comment by halal-beef** [comment]
I saw the gif u sent

**Comment by maj113** [comment]
mb why u still here
im just testing shit
